# erster teil des codes kuemmert sich um die Existenz z.B. wieviel RAM etc. 
# Erster Teil: Deployment (Existenz der App)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilates-website
  labels:
    app: pilates  
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: pilates
  template:
    metadata:
      labels:
        app: pilates
    spec:
      containers:
      - name: website-container
        # Docker hub name
        image: ayakhaleel/pilates-web:latest
        
        # ÄNDERUNG 2: Auf 'Always' ändern, damit er im Internet sucht
        imagePullPolicy: Always 
        
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---

# Zweiter Teil: Service (Erreichbarkeit)
apiVersion: v1
kind: Service
metadata:
  name: pilates-service
spec:
  selector:
    app: pilates
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort